# Generated by Django 5.0.4 on 2024-12-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_Development', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('father_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone_no', models.IntegerField()),
            ],
        ),
    ]
